name: "Deploy to PythonAnywhere"
description: "Push code to PythonAnywhere and reload the web app."

inputs:
  username:
    description: "PythonAnywhere username"
    required: true
  api_token:
    description: "PythonAnywhere API token"
    required: true
  domain:
    description: "PythonAnywhere domain"
    required: true
  deploy_secret:
    description: "Deploy security secret"
    required: true
  deploy_url:
    description: "Deploy API url"
    required: true

runs:
  using: "composite"
  steps:
    - name: Trigger deploy endpoint
      shell: bash
      run: |
        curl -X POST ${{ inputs.deploy_url }} -H "Authorization: Bearer ${{ inputs.deploy_secret }}"

    - name: Reload app via PythonAnywhere API
      shell: bash
      run: |
        curl -X POST https://www.pythonanywhere.com/api/v0/user/${{ inputs.username }}/webapps/${{ inputs.domain }}/reload/ \
          -H "Authorization: ${{ inputs.api_token }}"
